### ISSUE TITLE
Provide users with a pre-built docker image

### ISSUE THREAD

**Issue by freehck** [vinser/flibgolite#12]
Would be nice to have an official image on dockerhub or somewhere else, as it's one of the most convenient ways to deploy software.

**Comment by vinser** [comment]
I appreciate your contribution and ready to discuss your proposal.
I used containers in my [FLIBGO](https://github.com/vinser/flibgo) app.
The main goal of developing this one was to simplify usage by light release. They say better user experience :) For this purpose database was built in and the option to install the application as a Windows service or Linux daemon was made. So this app does not need any other software to run. 
As a matter of fact on Windows the app may be installed as a service with simple command `flibgolite -service install` and run with `flibgolite -service start` command. So ordinary users do not need to install Docker Desktop.
We may add it to Advance usage section. _Plenty is no plague_ ;)

**Comment by freehck** [comment]
Oh.. I supposed flibgo's obsolete, and this one is flibgoLITE because of sqLITE. :)

Nevermind. Flibgo doesn't work due to multiple reasons. One reason is varchars that happened to be too short for covers and plots. Was trying to fix by it modifying the schema manually, but eventually I stuck with problems of "incorrect string values". On the other side here's flibgolite using sqlite. Despite the fact it uses specifically the same schema, sqlite behaves differently than mariadb because it internally converts varchars to text, and text is much longer.

Okay. If you don't consider flibgo as obsolete, I could fill a bunch of bugs there in a while.

--

Bits about service. JFYI, "service install" doesn't work with alpine linux. It seems you're trying to use update-rc, that's not present there. Didn't test it with other distros.

--

Bits about docker. "Service install"... Well it's an interesting idea, but kinda strange. I don't think any maintainers will appreciate this approach. If you really want to simplify users' life, probably it would be better to create a flibgolite's distribuition. Two ways: either to create packages (at least rpm/deb, maybe with self-hosted repo), or to pack a container. Have got an opinion that Docker's easier and better than status quo.

Well I don't insist on docker for flibgolite. I already have my container. For me this issue is already closed.

**Comment by vinser** [comment]
Flibgo is not obsolete and I hope to update it with some todo features based on the results of this lightweight version  development.
--
Kardianos/service package used in flibgolite currently supports Windows, Linux/(systemd | Upstart | SysV | OpenRC), and OSX/Launchd. So alpine is in this list with its OpenRC. This package is used in more then 1000 Go repositories on GitHub. May be it's my bug.
--
Let's use Docker but I need realize how to make container distribution for dockerhub for different platforms. So for now users have to build container themselves.

**Comment by freehck** [comment]
If you switch to GitLab, I will help you with DockerHub and CI/CD.

**Comment by apavelm** [comment]
Docker image on DuckerHub will be very appreciated. Building docker images on NAS systems, like unRAID is not for what those systems were made. Please export/upload image to duckerHub. Thanks

**Comment by vinser** [comment]
@apavelm 
> Docker image on DockerHub will be very appreciated.
Added in release v2.2.3
