### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by MIG85** [vinser/flibgolite#21]
root@OpenWrt:/mnt/sda5/books$ ./flibgolite-linux-arm-6
I: 18:01:39 Service is running unix-systemv.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5ffc38]

goroutine 20 [running]:
github.com/vinser/flibgolite/pkg/stock.(*Handler).indexFB2Zip(0x165b740, {0x159eaf0, 0x46})
        /home/vinser/Dev/flibgolite/pkg/stock/stock.go:279 +0xa0c
github.com/vinser/flibgolite/pkg/stock.(*Handler).ScanDir.func1()
        /home/vinser/Dev/flibgolite/pkg/stock/stock.go:109 +0x40
created by github.com/vinser/flibgolite/pkg/stock.(*Handler).ScanDir
        /home/vinser/Dev/flibgolite/pkg/stock/stock.go:108 +0x9f0

root@OpenWrt:/mnt/sda5/books$ cat ./logs/scan.log
SERVICE: 2022/10/19 17:59:07 New acquisitions scanning started...
INFO:    2022/10/19 17:59:07 scanning folder /mnt/sda5/torrent/Downloads/Books/Flibusta.Net for new books.../n
DEBUG:   2022/10/19 17:59:07 stock.go:105: zip:  f.usr-524141-526015.zip
DEBUG:   2022/10/19 17:59:07 stock.go:251:
===========================================
File               :  524142.pdf
NonUTF8            :  false
Modified           :  2018-07-02 02:11:34 +0300 +0300
CRC32              :  3177836722
UncompressedSize64 :  26640417
===========================================
INFO:    2022/10/19 17:59:07 file 524142.pdf from f.usr-524141-526015.zip has unsupported format ".pdf"
DEBUG:   2022/10/19 17:59:07 stock.go:273: <nil>

**Comment by vinser** [comment]
Fixed in release v1.1.1

**Comment by vinser** [comment]
@MIG85 
Thanks for bug detailed description! I have no archives with pdf so bug was not discovered before your report
